services:
  imranslab-web:
    build:
      context: ../../
      dockerfile: docker/imranslab/Dockerfile
    container_name: imranslab-web
    restart: unless-stopped
    volumes:
      - ../../config/nginx/react-app.conf:/etc/nginx/conf.d/default.conf
    networks:
      - cloudflared

networks:
  cloudflared:
    external: true
    name: cloudflared